name: manga_reader
description: A lightweight manga reader with dictionary and Anki support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  file_picker: ^8.0.0
  photo_view: ^0.15.0
  sqflite: ^2.3.2
  path: ^1.9.0
  archive: ^3.4.10
  shared_preferences: ^2.2.2
  android_intent_plus: ^5.0.2
  http: ^1.2.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
