name: Android Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Dependencies
      run: |
        cd manga_reader
        flutter pub get

    - name: Build APK
      run: |
        cd manga_reader
        flutter build apk --release --split-per-abi

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: release-apks
        path: manga_reader/build/app/outputs/flutter-apk/*.apk
